"""Add sender_name to gmail_accounts

Revision ID: 2bb3d6b44b70
Revises: 
Create Date: 2026-04-04 19:20:26.197078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bb3d6b44b70'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gmail_accounts', sa.Column('sender_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gmail_accounts', 'sender_name')
    # ### end Alembic commands ###
